# Generated by Django 5.2 on 2025-07-05 14:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Club",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created",
                    models.DateTimeField(
                        auto_now_add=True, db_index=True, verbose_name="Дата создания"
                    ),
                ),
                (
                    "modified",
                    models.DateTimeField(
                        blank=True,
                        db_index=True,
                        null=True,
                        verbose_name="Дата изменения",
                    ),
                ),
                (
                    "book_title",
                    models.CharField(
                        max_length=255, unique=True, verbose_name="Название книги"
                    ),
                ),
                (
                    "book_authors",
                    models.CharField(max_length=255, verbose_name="Авторы книги"),
                ),
                ("publication_year", models.IntegerField(verbose_name="Год издания")),
                ("description", models.TextField(verbose_name="Описание книги")),
                (
                    "telegram_chat_link",
                    models.URLField(verbose_name="Ссылка на Telegram-чат"),
                ),
                (
                    "members",
                    models.ManyToManyField(
                        blank=True,
                        related_name="clubs",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Участники",
                    ),
                ),
                (
                    "owner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="owned_clubs",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Владелец клуба",
                    ),
                ),
            ],
            options={
                "verbose_name": "Книжный клуб",
                "verbose_name_plural": "Книжные клубы",
                "ordering": ["id"],
                "unique_together": {("book_title", "book_authors", "publication_year")},
            },
        ),
    ]
