# Generated by Django 5.2 on 2025-07-05 19:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("clubs", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="club",
            options={
                "ordering": ["id"],
                "verbose_name": "Book Club",
                "verbose_name_plural": "Book Clubs",
            },
        ),
        migrations.AlterField(
            model_name="club",
            name="book_authors",
            field=models.CharField(max_length=255, verbose_name="Book Authors"),
        ),
        migrations.AlterField(
            model_name="club",
            name="book_title",
            field=models.CharField(
                max_length=255, unique=True, verbose_name="Book Title"
            ),
        ),
        migrations.AlterField(
            model_name="club",
            name="description",
            field=models.TextField(verbose_name="Book Description"),
        ),
        migrations.AlterField(
            model_name="club",
            name="members",
            field=models.ManyToManyField(
                blank=True,
                related_name="clubs",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Members",
            ),
        ),
        migrations.AlterField(
            model_name="club",
            name="owner",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="owned_clubs",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Club Owner",
            ),
        ),
        migrations.AlterField(
            model_name="club",
            name="publication_year",
            field=models.IntegerField(verbose_name="Publication Year"),
        ),
        migrations.AlterField(
            model_name="club",
            name="telegram_chat_link",
            field=models.URLField(verbose_name="Link on Telegram chat"),
        ),
    ]
