# Generated by Django 5.2 on 2025-07-16 10:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("clubs", "0003_bookreview"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="bookreview",
            options={
                "ordering": ["-created"],
                "verbose_name": "Book Review",
                "verbose_name_plural": "Book Reviews",
            },
        ),
    ]
