# Generated by Django 5.2

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("clubs", "0004_alter_bookreview_options"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="club",
            unique_together=set(),
        ),
    ]
