# Generated by Django 5.2.15 on 2026-08-11 11:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clubs', '0005_remove_club_unique_together'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='club',
            name='max_chat_link',
            field=models.URLField(blank=True, verbose_name='Link on Max chat'),
        ),
        migrations.CreateModel(
            name='ClubRequest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Дата создания')),
                ('modified', models.DateTimeField(blank=True, db_index=True, null=True, verbose_name='Дата изменения')),
                ('book_title', models.CharField(max_length=255, verbose_name='Book Title')),
                ('book_authors', models.CharField(max_length=255, verbose_name='Book Authors')),
                ('publication_year', models.IntegerField(verbose_name='Publication Year')),
                ('description', models.TextField(verbose_name='Book Description')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('declined', 'Declined')], default='pending', max_length=16, verbose_name='Status')),
                ('telegram_chat_link', models.URLField(blank=True, verbose_name='Link on Telegram chat')),
                ('max_chat_link', models.URLField(blank=True, verbose_name='Link on Max chat')),
                ('admin_comment', models.TextField(blank=True, verbose_name='Admin Comment')),
                ('requester', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='club_requests', to=settings.AUTH_USER_MODEL, verbose_name='Requester')),
            ],
            options={
                'verbose_name': 'Club Request',
                'verbose_name_plural': 'Club Requests',
                'ordering': ['-created'],
            },
        ),
    ]
