# Generated by Django 5.2.15 on 2026-08-11 16:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("clubs", "0007_category"),
    ]

    operations = [
        migrations.AddField(
            model_name="club",
            name="category",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="clubs",
                to="clubs.category",
                verbose_name="Category",
            ),
        ),
        migrations.AddField(
            model_name="clubrequest",
            name="category",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="club_requests",
                to="clubs.category",
                verbose_name="Category",
            ),
        ),
    ]
