# Generated by Django 5.2.15 on 2026-08-14 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clubs', '0008_club_category_clubrequest_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='club',
            name='author_bio',
            field=models.TextField(blank=True, verbose_name='Author/Host Bio'),
        ),
        migrations.AddField(
            model_name='club',
            name='author_name',
            field=models.CharField(blank=True, max_length=255, verbose_name='Author/Host Name'),
        ),
        migrations.AddField(
            model_name='club',
            name='author_photo',
            field=models.ImageField(blank=True, null=True, upload_to='club_authors/', verbose_name='Author Photo'),
        ),
        migrations.AddField(
            model_name='club',
            name='club_type',
            field=models.CharField(choices=[('book', 'Book Club'), ('author', 'Author Club')], default='book', max_length=16, verbose_name='Club Type'),
        ),
        migrations.AddField(
            model_name='clubrequest',
            name='author_bio',
            field=models.TextField(blank=True, verbose_name='Author/Host Bio'),
        ),
        migrations.AddField(
            model_name='clubrequest',
            name='author_name',
            field=models.CharField(blank=True, max_length=255, verbose_name='Author/Host Name'),
        ),
        migrations.AddField(
            model_name='clubrequest',
            name='author_photo',
            field=models.ImageField(blank=True, null=True, upload_to='club_authors/', verbose_name='Author Photo'),
        ),
        migrations.AddField(
            model_name='clubrequest',
            name='club_type',
            field=models.CharField(choices=[('book', 'Book Club'), ('author', 'Author Club')], default='book', max_length=16, verbose_name='Club Type'),
        ),
        migrations.AlterField(
            model_name='club',
            name='book_title',
            field=models.CharField(max_length=255, verbose_name='Book Title'),
        ),
    ]
