"""
Generated by restcodegen (https://github.com/ValeriyMenshikov/restcodegen).

    source: {{ service_name|to_snake_case }}
    version: {{ version }}

    Do not edit the class manually.
"""

from __future__ import annotations

from typing import Any, Optional

from pydantic import AnyUrl, BaseModel, EmailStr, Field, RootModel


class Club(BaseModel):
    id: int
    book_title: str = Field(..., alias="bookTitle", max_length=255)
    book_authors: str = Field(..., alias="bookAuthors", max_length=255)
    publication_year: int = Field(..., alias="publicationYear", ge=-2147483648, le=2147483647)
    description: str = Field(..., title="Book Description")
    telegram_chat_link: AnyUrl = Field(..., alias="telegramChatLink", title="Link on Telegram chat")
    owner: int = Field(..., title="Club Owner")
    members: list[int]


class PaginatedClubList(BaseModel):
    count: int = Field(..., examples=[123])
    next: Optional[AnyUrl] = Field(None, examples=["http://api.example.org/accounts/?page=4"])
    previous: Optional[AnyUrl] = Field(None, examples=["http://api.example.org/accounts/?page=2"])
    results: list[Club]


class PatchedClub(BaseModel):
    id: Optional[int] = None
    book_title: Optional[str] = Field(None, alias="bookTitle", max_length=255)
    book_authors: Optional[str] = Field(None, alias="bookAuthors", max_length=255)
    publication_year: Optional[int] = Field(None, alias="publicationYear", ge=-2147483648, le=2147483647)
    description: Optional[str] = Field(None, title="Book Description")
    telegram_chat_link: Optional[AnyUrl] = Field(None, alias="telegramChatLink", title="Link on Telegram chat")
    owner: Optional[int] = Field(None, title="Club Owner")
    members: Optional[list[int]] = None


class TokenBlacklist(BaseModel):
    refresh: str


class TokenObtainPairWithProperMessage(BaseModel):
    username: str
    password: str


class TokenRefresh(BaseModel):
    access: str
    refresh: str


class User(BaseModel):
    id: int
    username: str = Field(
        ...,
        description="Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.",
        max_length=150,
        pattern="^[\\w.@+-]+$",
    )
    first_name: Optional[str] = Field(None, alias="firstName", max_length=150)
    last_name: Optional[str] = Field(None, alias="lastName", max_length=150)
    email: Optional[EmailStr] = Field(None, max_length=254, title="Email address")
    remote_addr: str = Field(..., alias="remoteAddr")


class UserRegister(BaseModel):
    username: str = Field(
        ...,
        description="Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.",
        max_length=150,
        pattern="^[\\w.@+-]+$",
    )
    password: str = Field(..., max_length=128)


class DocsSchemaRetrieveResponse200(RootModel[Optional[dict[str, Any]]]):
    root: Optional[dict[str, Any]] = None
