"""
Generated by restcodegen (https://github.com/ValeriyMenshikov/restcodegen).

    source: book_club
    version: 1.1.0

    Do not edit the class manually.
"""

from typing import Any

from httpx import Response
from restcodegen.restclient import Client

from clients.http.book_club.models.api_models import (
    Club,
    PaginatedClubList,
    PatchedClub,
)


class ClubsApi:
    def __init__(self, api_client: Client) -> None:
        self.api_client = api_client

    def get_api_v1_clubs(
        self,
        membership: str,
        page: int,
        page_size: int,
        search: str,
        **kwargs: Any,
    ) -> PaginatedClubList:
        """
        No summary description.

        Args:
            membership(str, optional): ...
            page(int, optional): A page number within the paginated result set.
            page_size(int, optional): Number of results to return per page.
            search(str, optional): ...
            **kwargs: Arguments supported by the httpx library (data, files, headers, etc.)

        Returns:
            PaginatedClubList: ...

        """

        response = self.get_api_v1_clubs_with_http_info(
            membership=membership,
            page=page,
            page_size=page_size,
            search=search,
            **kwargs,
        )
        return PaginatedClubList.model_validate_json(response.text)

    def get_api_v1_clubs_with_http_info(
        self,
        membership: str,
        page: int,
        page_size: int,
        search: str,
        **kwargs: Any,
    ) -> Response:
        """
        No summary description.

        Args:
            membership(str, optional): ...
            page(int, optional): A page number within the paginated result set.
            page_size(int, optional): Number of results to return per page.
            search(str, optional): ...
            **kwargs: Arguments supported by the httpx library (data, files, headers, etc.)

        Returns:
            Response: ...

        """
        # process the query parameters
        params_map = {
            "membership": membership,
            "page": page,
            "page_size": page_size,
            "search": search,
        }
        params = {k: v for k, v in params_map.items() if v}
        headers = kwargs.pop("headers", {})

        response = self.api_client.get(
            url="/api/v1/clubs/",
            params=params,
            headers=headers,
            **kwargs,
        )
        return response

    def post_api_v1_clubs(
        self,
        club: Club,
        **kwargs: Any,
    ) -> Club:
        """
        No summary description.

        Args:
            club(Club): ...
            **kwargs: Arguments supported by the httpx library (data, files, headers, etc.)

        Returns:
            Club: ...

        """

        response = self.post_api_v1_clubs_with_http_info(
            club=club,
            **kwargs,
        )
        return Club.model_validate_json(response.text)

    def post_api_v1_clubs_with_http_info(
        self,
        club: Club,
        **kwargs: Any,
    ) -> Response:
        """
        No summary description.

        Args:
            club(Club): ...
            **kwargs: Arguments supported by the httpx library (data, files, headers, etc.)

        Returns:
            Response: ...

        """
        headers = kwargs.pop("headers", {})

        content = club.model_dump_json(exclude_none=True, by_alias=True)
        headers.update({"Content-Type": "application/json"})

        response = self.api_client.post(
            url="/api/v1/clubs/",
            content=content,
            headers=headers,
            **kwargs,
        )
        return response

    def get_api_v1_clubs_id(
        self,
        id_: int,
        **kwargs: Any,
    ) -> Club:
        """
        No summary description.

        Args:
            id_(int, required): A unique integer value identifying this Book Club.
            **kwargs: Arguments supported by the httpx library (data, files, headers, etc.)

        Returns:
            Club: ...

        """

        response = self.get_api_v1_clubs_id_with_http_info(
            id_=id_,
            **kwargs,
        )
        return Club.model_validate_json(response.text)

    def get_api_v1_clubs_id_with_http_info(
        self,
        id_: int,
        **kwargs: Any,
    ) -> Response:
        """
        No summary description.

        Args:
            id_(int, required): A unique integer value identifying this Book Club.
            **kwargs: Arguments supported by the httpx library (data, files, headers, etc.)

        Returns:
            Response: ...

        """
        headers = kwargs.pop("headers", {})

        response = self.api_client.get(
            url=f"/api/v1/clubs/{id_}/",
            headers=headers,
            **kwargs,
        )
        return response

    def put_api_v1_clubs_id(
        self,
        club: Club,
        id_: int,
        **kwargs: Any,
    ) -> Club:
        """
        No summary description.

        Args:
            club(Club): ...
            id_(int, required): A unique integer value identifying this Book Club.
            **kwargs: Arguments supported by the httpx library (data, files, headers, etc.)

        Returns:
            Club: ...

        """

        response = self.put_api_v1_clubs_id_with_http_info(
            id_=id_,
            club=club,
            **kwargs,
        )
        return Club.model_validate_json(response.text)

    def put_api_v1_clubs_id_with_http_info(
        self,
        club: Club,
        id_: int,
        **kwargs: Any,
    ) -> Response:
        """
        No summary description.

        Args:
            club(Club): ...
            id_(int, required): A unique integer value identifying this Book Club.
            **kwargs: Arguments supported by the httpx library (data, files, headers, etc.)

        Returns:
            Response: ...

        """
        headers = kwargs.pop("headers", {})

        content = club.model_dump_json(exclude_none=True, by_alias=True)
        headers.update({"Content-Type": "application/json"})

        response = self.api_client.put(
            url=f"/api/v1/clubs/{id_}/",
            content=content,
            headers=headers,
            **kwargs,
        )
        return response

    def patch_api_v1_clubs_id(
        self,
        patched_club: PatchedClub,
        id_: int,
        **kwargs: Any,
    ) -> Club:
        """
        No summary description.

        Args:
            patched_club(PatchedClub): ...
            id_(int, required): A unique integer value identifying this Book Club.
            **kwargs: Arguments supported by the httpx library (data, files, headers, etc.)

        Returns:
            Club: ...

        """

        response = self.patch_api_v1_clubs_id_with_http_info(
            id_=id_,
            patched_club=patched_club,
            **kwargs,
        )
        return Club.model_validate_json(response.text)

    def patch_api_v1_clubs_id_with_http_info(
        self,
        patched_club: PatchedClub,
        id_: int,
        **kwargs: Any,
    ) -> Response:
        """
        No summary description.

        Args:
            patched_club(PatchedClub): ...
            id_(int, required): A unique integer value identifying this Book Club.
            **kwargs: Arguments supported by the httpx library (data, files, headers, etc.)

        Returns:
            Response: ...

        """
        headers = kwargs.pop("headers", {})

        content = patched_club.model_dump_json(exclude_none=True, by_alias=True)
        headers.update({"Content-Type": "application/json"})

        response = self.api_client.patch(
            url=f"/api/v1/clubs/{id_}/",
            content=content,
            headers=headers,
            **kwargs,
        )
        return response

    def delete_api_v1_clubs_id(
        self,
        id_: int,
        **kwargs: Any,
    ) -> Response:
        """
        No summary description.

        Args:
            id_(int, required): A unique integer value identifying this Book Club.
            **kwargs: Arguments supported by the httpx library (data, files, headers, etc.)

        Returns:
            None: ...

        """

        response = self.delete_api_v1_clubs_id_with_http_info(
            id_=id_,
            **kwargs,
        )
        return response

    def delete_api_v1_clubs_id_with_http_info(
        self,
        id_: int,
        **kwargs: Any,
    ) -> Response:
        """
        No summary description.

        Args:
            id_(int, required): A unique integer value identifying this Book Club.
            **kwargs: Arguments supported by the httpx library (data, files, headers, etc.)

        Returns:
            Response: ...

        """
        headers = kwargs.pop("headers", {})

        response = self.api_client.delete(
            url=f"/api/v1/clubs/{id_}/",
            headers=headers,
            **kwargs,
        )
        return response

    def post_api_v1_clubs_id__members_me(
        self,
        id_: int,
        **kwargs: Any,
    ) -> Response:
        """
        No summary description.

        Args:
            id_(int, required): A unique integer value identifying this Book Club.
            **kwargs: Arguments supported by the httpx library (data, files, headers, etc.)

        Returns:
            None: ...

        """

        response = self.post_api_v1_clubs_id__members_me_with_http_info(
            id_=id_,
            **kwargs,
        )
        return response

    def post_api_v1_clubs_id__members_me_with_http_info(
        self,
        id_: int,
        **kwargs: Any,
    ) -> Response:
        """
        No summary description.

        Args:
            id_(int, required): A unique integer value identifying this Book Club.
            **kwargs: Arguments supported by the httpx library (data, files, headers, etc.)

        Returns:
            Response: ...

        """
        headers = kwargs.pop("headers", {})

        response = self.api_client.post(
            url=f"/api/v1/clubs/{id_}/members/me/",
            headers=headers,
            **kwargs,
        )
        return response

    def delete_api_v1_clubs_id__members_me(
        self,
        id_: int,
        **kwargs: Any,
    ) -> Response:
        """
        No summary description.

        Args:
            id_(int, required): A unique integer value identifying this Book Club.
            **kwargs: Arguments supported by the httpx library (data, files, headers, etc.)

        Returns:
            None: ...

        """

        response = self.delete_api_v1_clubs_id__members_me_with_http_info(
            id_=id_,
            **kwargs,
        )
        return response

    def delete_api_v1_clubs_id__members_me_with_http_info(
        self,
        id_: int,
        **kwargs: Any,
    ) -> Response:
        """
        No summary description.

        Args:
            id_(int, required): A unique integer value identifying this Book Club.
            **kwargs: Arguments supported by the httpx library (data, files, headers, etc.)

        Returns:
            Response: ...

        """
        headers = kwargs.pop("headers", {})

        response = self.api_client.delete(
            url=f"/api/v1/clubs/{id_}/members/me/",
            headers=headers,
            **kwargs,
        )
        return response
