"""
Generated by restcodegen (https://github.com/ValeriyMenshikov/restcodegen).

    source: book_club
    version: 1.1.0

    Do not edit the class manually.
"""

from typing import Any

from httpx import Response
from restcodegen.restclient import Client

from clients.http.book_club.models.api_models import (
    DocsSchemaRetrieveResponse200,
)


class DocsApi:
    def __init__(self, api_client: Client) -> None:
        self.api_client = api_client

    def get_api_v1_docs_schema(
        self,
        format_: str,
        lang: str,
        **kwargs: Any,
    ) -> DocsSchemaRetrieveResponse200:
        """
        No summary description.

        Args:
            format_(str, optional): ...
            lang(str, optional): ...
            **kwargs: Arguments supported by the httpx library (data, files, headers, etc.)

        Returns:
            DocsSchemaRetrieveResponse200: ...

        """

        response = self.get_api_v1_docs_schema_with_http_info(
            format_=format_,
            lang=lang,
            **kwargs,
        )
        return DocsSchemaRetrieveResponse200.model_validate_json(response.text)

    def get_api_v1_docs_schema_with_http_info(
        self,
        format_: str,
        lang: str,
        **kwargs: Any,
    ) -> Response:
        """
        No summary description.

        Args:
            format_(str, optional): ...
            lang(str, optional): ...
            **kwargs: Arguments supported by the httpx library (data, files, headers, etc.)

        Returns:
            Response: ...

        """
        # process the query parameters
        params_map = {
            "format": format_,
            "lang": lang,
        }
        params = {k: v for k, v in params_map.items() if v}
        headers = kwargs.pop("headers", {})

        response = self.api_client.get(
            url="/api/v1/docs/schema/",
            params=params,
            headers=headers,
            **kwargs,
        )
        return response
