"""
Generated by restcodegen (https://github.com/ValeriyMenshikov/restcodegen).

    source: book_club
    version: 1.1.0

    Do not edit the class manually.
"""

from typing import Any

from httpx import Response
from restcodegen.restclient import Client

from clients.http.book_club.models.api_models import (
    User,
    UserRegister,
)


class UsersApi:
    def __init__(self, api_client: Client) -> None:
        self.api_client = api_client

    def get_api_v1_users_me(
        self,
        **kwargs: Any,
    ) -> User:
        """
        No summary description.

        Args:
            **kwargs: Arguments supported by the httpx library (data, files, headers, etc.)

        Returns:
            User: ...

        """

        response = self.get_api_v1_users_me_with_http_info(
            **kwargs,
        )
        return User.model_validate_json(response.text)

    def get_api_v1_users_me_with_http_info(
        self,
        **kwargs: Any,
    ) -> Response:
        """
        No summary description.

        Args:
            **kwargs: Arguments supported by the httpx library (data, files, headers, etc.)

        Returns:
            Response: ...

        """
        headers = kwargs.pop("headers", {})

        response = self.api_client.get(
            url="/api/v1/users/me/",
            headers=headers,
            **kwargs,
        )
        return response

    def delete_api_v1_users_me(
        self,
        **kwargs: Any,
    ) -> Response:
        """
        No summary description.

        Args:
            **kwargs: Arguments supported by the httpx library (data, files, headers, etc.)

        Returns:
            None: ...

        """

        response = self.delete_api_v1_users_me_with_http_info(
            **kwargs,
        )
        return response

    def delete_api_v1_users_me_with_http_info(
        self,
        **kwargs: Any,
    ) -> Response:
        """
        No summary description.

        Args:
            **kwargs: Arguments supported by the httpx library (data, files, headers, etc.)

        Returns:
            Response: ...

        """
        headers = kwargs.pop("headers", {})

        response = self.api_client.delete(
            url="/api/v1/users/me/",
            headers=headers,
            **kwargs,
        )
        return response

    def post_api_v1_users_register(
        self,
        user_register: UserRegister,
        **kwargs: Any,
    ) -> UserRegister:
        """
        No summary description.

        Args:
            user_register(UserRegister): ...
            **kwargs: Arguments supported by the httpx library (data, files, headers, etc.)

        Returns:
            UserRegister: ...

        """

        response = self.post_api_v1_users_register_with_http_info(
            user_register=user_register,
            **kwargs,
        )
        return UserRegister.model_validate_json(response.text)

    def post_api_v1_users_register_with_http_info(
        self,
        user_register: UserRegister,
        **kwargs: Any,
    ) -> Response:
        """
        No summary description.

        Args:
            user_register(UserRegister): ...
            **kwargs: Arguments supported by the httpx library (data, files, headers, etc.)

        Returns:
            Response: ...

        """
        headers = kwargs.pop("headers", {})

        content = user_register.model_dump_json(exclude_none=True, by_alias=True)
        headers.update({"Content-Type": "application/json"})

        response = self.api_client.post(
            url="/api/v1/users/register/",
            content=content,
            headers=headers,
            **kwargs,
        )
        return response
