"""
Generated by restcodegen (https://github.com/ValeriyMenshikov/restcodegen).

    source: book_club
    version: 1.1.0

    Do not edit the class manually.
"""

from clients.http.book_club.apis.auth_api import AuthApi
from clients.http.book_club.apis.clubs_api import ClubsApi
from clients.http.book_club.apis.docs_api import DocsApi
from clients.http.book_club.apis.users_api import UsersApi


__all__ = [
    "AuthApi",
    "ClubsApi",
    "DocsApi",
    "UsersApi",
]
