# Generated by Django 5.2 on 2026-06-22 00:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('a12n', '0001_initial'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='emailverificationcode',
            new_name='a12n_emailv_email_3499cb_idx',
            old_name='a12n_emailv_email_6f3ef4_idx',
        ),
        migrations.AlterField(
            model_name='emailverificationcode',
            name='code',
            field=models.CharField(editable=False, max_length=4),
        ),
    ]
