# Generated by Django 5.2.15 on 2026-07-12 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("a12n", "0002_alter_code_max_length"),
    ]

    operations = [
        migrations.AlterField(
            model_name="emailverificationcode",
            name="id",
            field=models.AutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
    ]
