# Generated by Django 5.2.15 on 2026-08-11 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="is_reading_list_public",
            field=models.BooleanField(
                default=False, verbose_name="Reading list is public"
            ),
        ),
    ]
