# Generated by Django 5.2.15 on 2026-08-11 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0002_user_is_reading_list_public"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="is_reading_list_public",
            field=models.BooleanField(
                db_default=False, default=False, verbose_name="Reading list is public"
            ),
        ),
    ]
