name: Testing Backend

on:
  push:
    paths:
      - 'backend/**'
      - '.github/workflows/backend.yml'

defaults:
  run:
    working-directory: ./backend

permissions:
  contents: write
  pages: write
  id-token: write

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/setup-project
      - name: install dev dependencies
        run: |
          task install-dev-deps
        shell: bash
      - run: task lint
        
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/setup-project
      - name: install dev dependencies
        run: |
          task install-dev-deps
        shell: bash